theme: jekyll-theme-midnight
locale : "en-US"
title : "SmartGroupware"
title_separator : "-"
name : "Sanghoon Jeong"
description : "Spring based webmail group ware"
url : "https://berrycore.github.ip/SmartGroupware
